### ISSUE TITLE
After installing the ca certificate, chrome prompt - privacy Settings error, your connection is not private

### ISSUE THREAD

**Issue by chenxi2008** [OfficeDev/Word-Add-in-JS-Redact#11]
安装了ca证书后，chrome提示-隐私设置错误，您的连接不是私密连接
why you close my issue? you can't  solve the question?

**Comment by Rick-Kirkham** [comment]
Please provide more details. What are the steps leading up to the error. Where do you see the error? Why do you have Chrome open? The add-in runs in Microsoft Word 2016. It does not run in a browser.
