### ISSUE TITLE
how do I run on server not local 

### ISSUE THREAD

**Issue by KyungsooHong** [OfficeDev/Word-Add-in-JS-Redact#5]
Hello, 

I succeeded to run on my local machine with the shared folder.
and I run it on the remote server, 
but I can't load it properly. 
I changed all 8088 to my URL.
and I still keep shared folder and delete all except XML file(word-add-in-js-redact-manifest.xml)

is it correct???

**Comment by Rick-Kirkham** [comment]
Did you change the URLs inside the manifest to your new URL?

**Comment by KyungsooHong** [comment]
my bad, somehow seems my windows had the problem at that moment, it works well
